export const zillaUpazillaData = {
  Joypurhat: ["Akkelpur", "Joypurhat Sadar", "Kalai", "Khetlal", "Panchbibi"],
  Bogura: [
    "Adamdighi",
    "Bogura Sadar",
    "Dhunat",
    "Dhupchanchia",
    "Gabtali",
    "Kahaloo",
    "Nandigram",
    "Sariakandi",
    "Shajahanpur",
    "Sherpur",
    "Shibganj",
    "Sonatola",
  ],
  Naogaon: [
    "Atrai",
    "Badalgachhi",
    "Manda",
    "Dhamoirhat",
    "Mohadevpur",
    "Naogaon Sadar",
    "Niamatpur",
    "Patnitala",
    "Porsha",
    "Raninagar",
    "Sapahar",
  ],
  Natore: [
    "Bagatipara",
    "Baraigram",
    "Gurudaspur",
    "Lalpur",
    "Natore Sadar",
    "Singra",
    "Naldanga",
  ],
  Nawabganj: [
    "Bholahat",
    "Gomastapur",
    "Nachole",
    "Nawabganj Sadar",
    "Shibganj",
  ],
  Pabna: [
    "Atgharia",
    "Bera",
    "Bhangura",
    "Chatmohar",
    "Faridpur",
    "Ishwardi",
    "Pabna Sadar",
    "Santhia",
    "Sujanagar",
  ],
  Sirajganj: [
    "Belkuchi",
    "Chauhali",
    "Kamarkhanda",
    "Kazipur",
    "Raiganj",
    "Shahjadpur",
    "Sirajganj Sadar",
    "Tarash",
    "Ullahpara",
  ],
  Rajshahi: [
    "Bagha",
    "Bagmara",
    "Charghat",
    "Durgapur",
    "Godagari",
    "Mohanpur",
    "Paba",
    "Puthia",
    "Tanore",
  ],
  Dinajpur: [
    "Birampur",
    "Birganj",
    "Biral",
    "Bochaganj",
    "Chirirbandar",
    "Phulbari",
    "Ghoraghat",
    "Hakimpur",
    "Kaharole",
    "Khansama",
    "Dinajpur Sadar",
    "Nawabganj",
    "Parbatipur",
  ],
  Gaibandha: [
    "Phulchhari",
    "Gaibandha Sadar",
    "Gobindaganj",
    "Palashbari",
    "Sadullapur",
    "Sughatta",
    "Sundarganj",
  ],
  Kurigram: [
    "Bhurungamari",
    "Char Rajibpur",
    "Chilmari",
    "Phulbari",
    "Kurigram Sadar",
    "Nageshwari",
    "Rajarhat",
    "Raomari",
    "Ulipur",
  ],
  Lalmonirhat: [
    "Aditmari",
    "Hatibandha",
    "Kaliganj",
    "Lalmonirhat Sadar",
    "Patgram",
  ],
  Nilphamari: [
    "Dimla",
    "Domar",
    "Jaldhaka",
    "Kishoreganj",
    "Nilphamari Sadar",
    "Saidpur",
  ],
  Panchagarh: ["Atwari", "Boda", "Debiganj", "Panchagarh Sadar", "Tetulia"],
  Rangpur: [
    "Badarganj",
    "Gangachhara",
    "Kaunia",
    "Rangpur Sadar",
    "Mithapukur",
    "Pirgachha",
    "Pirganj",
    "Taraganj",
  ],
  Thakurgaon: [
    "Baliadangi",
    "Haripur",
    "Pirganj",
    "Ranisankail",
    "Thakurgaon Sadar",
  ],
  Dhaka: ["Dhamrai", "Dohar", "Keraniganj", "Nawabganj", "Savar"],
  Gazipur: ["Gazipur Sadar", "Kaliakair", "Kaliganj", "Kapasia", "Sreepur"],
};
